### ISSUE TITLE
Service not created for 32 bit Windows workstation

### ISSUE THREAD

**Issue by keenick** [backuppc/cygwin-rsyncd#1]
4 workstations- 3 are 64 bit and 3.1.2.0 and 3.1.2.1 both install ok
One 32 bit workstation , the rsync service is not being created. A check of the rsync file in /bin says that is is the wrong type. (64 bit) and will not run on the 32 bit computer. 
Installer is very fast and I cannot get the output from the "Show Details"
If there is a install log, I will provide if you can tell me where it is located.
The 32 bit workstation, I could not get 3.1.2.0 to install either, I have reverted back and still running 3.0.9.0 and deleted the blat stuff as it was triggering the antivirus.

**Comment by craigbarratt** [comment]
Thanks for reporting this.  Yes, 3.2.1.x uses some 64 bit libraries / executables.  3.0.9.x uses 32 bit libraries / executables.  So your workaround is the right one - use 3.0.9.x from SourceForge for 32 bit windows installs.

The 3.0.9.0 release is here: https://sourceforge.net/projects/backuppc/files/cygwin-rsyncd/3.0.9.0.
