### ISSUE TITLE
c:/Users vs /cygdrive/c/Users

### ISSUE THREAD

**Issue by pdugas** [backuppc/cygwin-rsyncd#4]
Should the `path` setting in the commented out `[docs]` example in the distributed `rsyncd.conf` be changed? I followed its lead when creating a `[users]` share since that's all I'm backing up and set `path = c:/Users` initially. It took me an embarrassingly long time to figure out I needed to change that to `path = /cygdrive/c/Users`. I wonder if I'm not the only noob to get tripped up by this.

**Comment by craigbarratt** [comment]
Good point.  I'll update that on the next release, which is overdue for a refresh.  I didn't build the current installer package, but I'll look into building it (using `nsis`).

**Comment by pdugas** [comment]
Now that I think of it, I wonder if it would be possible to somehow support private forks to allow us to build personalized installers that include our customized configs.Maybe even add the firewall rule too. Dreaming aloud as I'm looking down the barrel of deploying to more than a few machines. lol

**Comment by craigbarratt** [comment]
I just updated the repository with newer versions of `rsync.exe` and `cygwin`, and fixed the commented example in `rsyncd.conf`.

It's pretty easy to customize and build your own site-specific installer using `nsis`.

**Comment by pdugas** [comment]
Thanks much for your effort on this project. Much appreciated.
