### ISSUE TITLE
Add Firewall Rule

### ISSUE THREAD

**Issue by pdugas** [backuppc/cygwin-rsyncd#5]
The powershell command to create a suitable firewall is below in case there's any way to run something like this in the installer. Would be nifty to prompt for an optional IP and add `-RemoteAddress x.x.x.x` too.

```
New-NetFirewallRule -DisplayName "Allow Inbound TCP 873 for RSYNCD" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 873 -Program C:\rsyncd\bin\rsync.exe -Profile Domain,Private
```

**Comment by craigbarratt** [comment]
This seems out of scope.  But as you note it would be easy for someone to make their own site-specific package that installs a firewall like you suggest.

**Comment by pdugas** [comment]
No argument.
